### ISSUE TITLE
HTTP502 Bad gateway la accesarea linkului http://scrabble.grep.ro

### ISSUE THREAD

**Issue by adinnaplus** [mgax/dexonline-scrabble#4]
Salut,

S-a mutat domeniul? Cand accesez http://scrabble.grep.ro primesc Bad Gateway.

Mersi,
Adina

**Comment by mgax** [comment]
Right, am oprit serverul de curând, nu credeam că îl folosește cineva :) Îl fac la loc săptămâna viitoare, promit!

**Comment by mgax** [comment]
@adinnaplus gata, e înapoi în viață :)
